### ISSUE TITLE
I can't build it using setup.py. the error message is " No such file or directory: 'spec-mount-dir'"

### ISSUE THREAD

**Issue by manggoguy** [vusec/instrumentation-infra#3]
Running setup.py using " ./setup.py run --build spec2006 deltatags", the error occurs. 
The error message is below.
15:14:39 [CRITICAL] unkown error
Traceback (most recent call last):
  File "/home/mok/tool/deltapointers/infra/infra/setup.py", line 769, in _run_command
    self._run_run()
  File "/home/mok/tool/deltapointers/infra/infra/setup.py", line 698, in _run_run
    self._run_build()
  File "/home/mok/tool/deltapointers/infra/infra/setup.py", line 575, in _run_build
    target.fetch(self.ctx)
  File "/home/mok/tool/deltapointers/infra/infra/targets/spec2006/__init__.py", line 199, in fetch
    os.chdir(self.source)
FileNotFoundError: [Errno 2] No such file or directory: 'spec-mount-dir'

I think it is related to spec2006. I don't know much about this tool because I haven't  used it, 
Do I have to install SPEC2006 first?

**Comment by taddeus** [comment]
You will need to provide SPEC2006 yourself (we cannot package it because it is not open-source) by editing setup.py [here](https://github.com/vusec/deltapointers/blob/master/setup.py#L31). Possible installation options are [here](https://instrumentation-infra.readthedocs.io/en/master/targets.html#infra.targets.SPEC2006).

**Comment by manggoguy** [comment]
Thanks! I thought it was open-source.
